name: Deploy to Zephyr Cloud

on:
  push:
    branches:
      - main

env:
  ZE_SECRET_TOKEN: ${{ secrets.ZEPHYR_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build remote
        working-directory: ./remote
        run: |
          npm ci
          npm run build

      - name: Build host
        working-directory: ./host
        run: |
          npm ci
          npm run build
